INSERT INTO ers_users (ERS_USERNAME, USER_EMAIL, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE_ID)
	VALUES ('emp1', 'emp1@emp.com', 'emp1', 'first', 'last', 1);

INSERT INTO ers_users (ERS_USERNAME, USER_EMAIL, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE_ID)
	VALUES ('emp2', 'emp2@emp.com', 'emp2', 'first', 'last', 1);
	
INSERT INTO ers_users (ERS_USERNAME, USER_EMAIL, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE_ID)
	VALUES ('man1', 'man1@man.com', 'man1', 'first', 'last', 2);
	
INSERT INTO ers_users (ERS_USERNAME, USER_EMAIL, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE_ID)
	VALUES ('man2', 'man2@man.com', 'man2', 'first', 'last', 2);
	
INSERT INTO ers_reimbursement (REIMB_AMOUNT, REIMB_SUBMITTED, REIMB_DESCRIPTION, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID)
	VALUES (300.20, CURRENT_TIMESTAMP, 'Some Description', 1, 1, 1);
	
INSERT INTO ers_reimbursement (REIMB_AMOUNT, REIMB_SUBMITTED, REIMB_DESCRIPTION, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID)
	VALUES (100.00, CURRENT_TIMESTAMP, 'Some Description', 2, 1, 1);
	
INSERT INTO ers_reimbursement (REIMB_AMOUNT, REIMB_SUBMITTED, REIMB_DESCRIPTION, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID)
	VALUES (3230.20, CURRENT_TIMESTAMP, 'Some Manager Description', 3, 1, 1);