DROP TABLE ERS_REIMBURSEMENT;
DROP TABLE ERS_USERS;
DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_REIMBURSEMENT_STATUS;

CREATE TABLE ERS_REIMBURSEMENT_STATUS (
	REIMB_STATUS_ID INT PRIMARY KEY,
	REIMB_STATUS VARCHAR(10) UNIQUE
);

INSERT INTO ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID, REIMB_STATUS) VALUES (1, 'PENDING');
INSERT INTO ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID, REIMB_STATUS) VALUES (2, 'APPROVED');
INSERT INTO ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID, REIMB_STATUS) VALUES (3, 'DENIED');

CREATE TABLE ERS_REIMBURSEMENT_TYPE (
	REIMB_TYPE_ID INT PRIMARY KEY,
	REIMB_TYPE VARCHAR(10) UNIQUE
);

INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (1, 'LODGING');
INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (2, 'TRAVEL');
INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (3, 'FOOD');
INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (4, 'OTHER');

CREATE TABLE ERS_USER_ROLES (
	ERS_USERS_ROLE_ID INT PRIMARY KEY,
	USER_ROLE VARCHAR(20) UNIQUE
);

INSERT INTO ERS_USER_ROLES (ERS_USERS_ROLE_ID, USER_ROLE) VALUES (1, 'EMPLOYEE');
INSERT INTO ERS_USER_ROLES (ERS_USERS_ROLE_ID, USER_ROLE) VALUES (2, 'FINANCE_MANAGER');

CREATE TABLE ERS_USERS (
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) UNIQUE,
	ERS_PASSWORD VARCHAR(50),
	USER_FIRST_NAME VARCHAR(100),
	USER_LAST_NAME VARCHAR(100),
	USER_EMAIL VARCHAR(150) UNIQUE,
	USER_ROLE_ID INT REFERENCES ERS_USER_ROLES(ERS_USERS_ROLE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT (
	REIMB_ID SERIAL PRIMARY KEY,
	REIMB_AMOUNT NUMERIC(10,2),
	REIMB_SUBMITTED TIMESTAMP,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	--REIMB_RECEIPT BYTEA,
	REIMB_AUTHOR INT REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_RESOLVER INT REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_STATUS_ID INT REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
	REIMB_TYPE_ID INT REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);